// ===== 1. 曲库数据 =====
// 分类 = 对象，歌 = 对象，整个曲库 = 数组套数组
// mid 是歌曲在QQ音乐里的唯一编号；想加歌就往对应分类里加一行
var categories = [
    {
        name: '空间站「黑塔」& 星穹列车',
        icon: '🛰️',
        songs: [
            { name: '太空漫步', singer: 'HOYO-MiX', mid: '003RbshY3dnyQk', interval: 115 },
            { name: '好戏开场', singer: 'HOYO-MiX', mid: '00216nXv4ZCofw', interval: 56 },
            { name: '即兴演出', singer: 'HOYO-MiX', mid: '000Raas82YYSRl', interval: 86 },
            { name: '科幻小说', singer: 'HOYO-MiX', mid: '000KBt3H3lSJ3R', interval: 101 },
            { name: '危机预知', singer: 'HOYO-MiX', mid: '001i8bNP34A6vX', interval: 109 },
            { name: '一触即发', singer: 'HOYO-MiX', mid: '000Ex6Mn0oJwK5', interval: 74 },
            { name: '灾虐的黎明', singer: 'HOYO-MiX', mid: '002b7n8k4CXjX3', interval: 104 },
            { name: '盐渍月亮', singer: 'HOYO-MiX', mid: '0046VGOn2xOMX0', interval: 43 },
            { name: '时间线', singer: 'HOYO-MiX', mid: '000wsbzd2KwNK0', interval: 188 },
            { name: '踏上旅途', singer: 'HOYO-MiX / Anthony Lynch', mid: '004cDsSq1yMUII', interval: 64 },
            { name: '纯真年代 Age of Innocence', singer: 'HOYO-MiX', mid: '001udiOX2avi7g', interval: 88 },
            { name: '绮金年代 Age of Opulence', singer: 'HOYO-MiX', mid: '002bxrc706evxh', interval: 100 },
            { name: '奇情异想的绅士 A Gentleman\'s Fantasy', singer: 'HOYO-MiX', mid: '001B3Vid27wzJ8', interval: 103 },
            { name: '不可思议 In Disbelief', singer: 'HOYO-MiX', mid: '002mNM4O1VSlQl', interval: 125 },
            { name: '异形容器 Aberrant Receptacle', singer: 'HOYO-MiX', mid: '000i5okl3FLJxO', interval: 101 },
            { name: '睡眠行走 Sleepwalking', singer: 'HOYO-MiX', mid: '001vNPR71vjic9', interval: 153 },
            { name: '心灵电波 Neuropulse', singer: 'HOYO-MiX', mid: '0022aRWs3Hh2aj', interval: 86 },
            { name: '幽闭恐惧 Lurking Dread', singer: 'HOYO-MiX', mid: '004LFQHC1ZmzDL', interval: 177 },
            { name: '扑朔迷离 Shadows of Enigma', singer: 'HOYO-MiX', mid: '0026yGDN3Hs5dQ', interval: 92 },
            { name: '宇宙殉情时 Cosmic Sacrifice for Love', singer: 'HOYO-MiX', mid: '002HeZQu36wi4p', interval: 100 },
            { name: '星穹铁道 Star Rail', singer: 'HOYO-MiX', mid: '003Ctvvf2JRpMS', interval: 69 },
            { name: '赛前热身 Warm Up', singer: 'HOYO-MiX', mid: '002kOLLM2hsQM9', interval: 58 },
            { name: '你追我赶 Neck-And-Neck', singer: 'HOYO-MiX', mid: '001xJawU2P7k0k', interval: 71 }
        ]
    },
    {
        name: '雅利洛-Ⅵ',
        icon: '❄️',
        songs: [
            { name: '野火 Wildfire', singer: 'HOYO-MiX / Jonathan Steingard', mid: '004XiKv82HcAGt', interval: 218 },
            { name: '野火 Wildfire', singer: 'HOYO-MiX', mid: '003Yh3iL3kcg4R', interval: 218 },
            { name: '余烬 Embers', singer: 'HOYO-MiX', mid: '000E5XpW1jLwW9', interval: 82 },
            { name: '炉火 Hearthfire', singer: 'HOYO-MiX', mid: '0033ttwk30IF3m', interval: 159 },
            { name: '喧哗 Streets Abuzz', singer: 'HOYO-MiX', mid: '004CHw9z0j1AXu', interval: 75 },
            { name: '苍逝冷阳 Faded Sun', singer: 'HOYO-MiX', mid: '001J6mEq2NFO0O', interval: 81 },
            { name: '寒径 Frosty Trail', singer: 'HOYO-MiX', mid: '000H2NZq0Hz0bI', interval: 100 },
            { name: '秩序 Order', singer: 'HOYO-MiX', mid: '0008NOsl33TOA5', interval: 115 },
            { name: '破冬而行 Braving the Cold', singer: 'HOYO-MiX', mid: '002DZN6E1OWdaQ', interval: 119 },
            { name: '暖阳 Warm Sun', singer: 'HOYO-MiX', mid: '0022Pp5P1pizY6', interval: 89 },
            { name: '酣眠 Sleep Tight', singer: 'HOYO-MiX', mid: '004FC8Pt173K0v', interval: 109 },
            { name: '静雪 Silent', singer: 'HOYO-MiX', mid: '001QHQHV0Sl5Kl', interval: 78 },
            { name: '冽风 Cutting Mistral', singer: 'HOYO-MiX', mid: '000ZGsgc2ftGql', interval: 116 },
            { name: '锻弦 Tempered Cord', singer: 'HOYO-MiX', mid: '0033TBV51e0X1A', interval: 109 },
            { name: '坚冰 Dense Floe', singer: 'HOYO-MiX', mid: '004M8BKr3LIlAg', interval: 139 },
            { name: '雪落无痕 Traceless Drift', singer: 'HOYO-MiX', mid: '002CjeHZ1WvhMB', interval: 124 },
            { name: '旧日之影 Ghost From the Past', singer: 'HOYO-MiX', mid: '001iu4i14RAJjz', interval: 77 },
            { name: '沉霜 Sinking Hoarfrost', singer: 'HOYO-MiX', mid: '000Ax2OQ0f18l7', interval: 103 },
            { name: '火种 Kindling', singer: 'HOYO-MiX', mid: '003RGDrt07hDA8', interval: 132 },
            { name: '地下 Underground', singer: 'HOYO-MiX', mid: '003SFTOj1BLZUC', interval: 107 },
            { name: '熛焱 Blaze', singer: 'HOYO-MiX', mid: '000wIT111MwP6s', interval: 78 },
            { name: '战幕将启 Conflict Undraped', singer: 'HOYO-MiX', mid: '001ybwEy0ULs5B', interval: 98 },
            { name: '泪凝 Crystal Tears', singer: 'HOYO-MiX', mid: '001U5dXP0lscYq', interval: 130 },
            { name: '余温 Lingering Heat', singer: 'HOYO-MiX', mid: '004WEh7u0njcwR', interval: 103 },
            { name: '迷漫 Thick Haze', singer: 'HOYO-MiX', mid: '0043R5fe1lep8X', interval: 123 },
            { name: '教父 Godfather', singer: 'HOYO-MiX', mid: '000Tet6l0ueQzx', interval: 107 },
            { name: '寒潮之下 Eternal Freeze', singer: 'HOYO-MiX', mid: '003qaJ2s094a0j', interval: 102 },
            { name: '永冬 Everwinter', singer: 'HOYO-MiX', mid: '0001txe13gUVo5', interval: 97 },
            { name: '严寒行军 Frozen March', singer: 'HOYO-MiX', mid: '00150Mpz2PgvfA', interval: 112 },
            { name: '命途 Fate', singer: 'HOYO-MiX', mid: '003MHjSS17l1Vk', interval: 127 },
            { name: '陷阵无回 A Trap With No Return', singer: 'HOYO-MiX', mid: '000Bs53Z48N5lT', interval: 65 },
            { name: '地底之谜 Subterranean Enigma', singer: 'HOYO-MiX', mid: '001IqWaK2o3rLa', interval: 65 },
            { name: '冬城珍宝 Everwinter\'s Collection', singer: 'HOYO-MiX', mid: '001OhA6i0Q93TZ', interval: 64 },
            { name: '寒铁暖阳 Cold Iron, Warming Sun', singer: 'HOYO-MiX', mid: '003vb6pi0n28aX', interval: 85 },
            { name: '竞技的舞台 Battle Arena', singer: 'HOYO-MiX', mid: '002ihHXv3chxbF', interval: 86 },
            { name: '欢迎来到「以太战线」！ Welcome to Aetherium Wars!', singer: 'HOYO-MiX', mid: '003Jq5D20Hlb3q', interval: 54 },
            { name: '对决！冠军候补 Battle! Championship Contender', singer: 'HOYO-MiX', mid: '001bjP3E39Wh4f', interval: 84 },
            { name: '决胜的舞台 Coliseum of Victory', singer: 'HOYO-MiX', mid: '003UXptG1KrD4m', interval: 105 },
            { name: '对决！锦标赛的决胜者 Battle! Tournament Winner', singer: 'HOYO-MiX', mid: '003Oix6H4FHIIm', interval: 101 },
            { name: '对决！冠军首席 Battle! Ultimate Champion', singer: 'HOYO-MiX', mid: '001kMqbG1PvEHf', interval: 93 },
            { name: '对决！雪山之巅的王者 Battle! King of the Snowy Hill', singer: 'HOYO-MiX', mid: '003eQAsf1GEeEr', interval: 95 }
        ]
    },
    {
        name: '仙舟「罗浮」',
        icon: '🏮',
        songs: [
            { name: '水龙吟 Samudrartha', singer: 'HOYO-MiX / 优素Yusuf', mid: '000dVTEG1nhhGi', interval: 172 },
            { name: '水龙吟 Samudrartha (伴奏)', singer: 'HOYO-MiX', mid: '003Uzx8i1wMZS2', interval: 172 },
            { name: '天下熙熙 Anthropic Domain', singer: 'HOYO-MiX', mid: '003JOBYG0JqHIc', interval: 104 },
            { name: '邀挽明月成宵宴 Lustrous Moonlight', singer: 'HOYO-MiX', mid: '003agLQ20FTzLF', interval: 121 },
            { name: '雷车动地 Thundering Chariot', singer: 'HOYO-MiX', mid: '001Tz7pa3bgyi7', interval: 102 },
            { name: '云阵四合 Cumulus Formations', singer: 'HOYO-MiX', mid: '001GLvZ32cpybi', interval: 97 },
            { name: '星文照旅魂 Ave Astra et Viator', singer: 'HOYO-MiX', mid: '003HYs2v04bkFO', interval: 112 },
            { name: '襟怀玉界 Warden of Jade', singer: 'HOYO-MiX', mid: '000IU1DG4Aj1vp', interval: 114 },
            { name: '锋镝阵中自在身 Into the Breach', singer: 'HOYO-MiX', mid: '0041gmPM1bELWg', interval: 120 },
            { name: '猎手的预视 Hunter\'s Intuition', singer: 'HOYO-MiX', mid: '002ujqqC0btxo0', interval: 101 },
            { name: '片时酣 Transient Jubilation', singer: 'HOYO-MiX', mid: '000GakDW0mJ2FZ', interval: 85 },
            { name: '俯仰穷观 Upon the Firmament', singer: 'HOYO-MiX', mid: '001s6fHV4XjqcO', interval: 108 },
            { name: '玲珑工巧 Exquisite Ingenuity', singer: 'HOYO-MiX', mid: '000Tt39o0jhkKt', interval: 120 },
            { name: '折冲妙算 Fabulous Foresight', singer: 'HOYO-MiX', mid: '00361W1Q17AZP4', interval: 120 },
            { name: '天火同人 Divine Camaraderie', singer: 'HOYO-MiX', mid: '002G88ZR4L4JdL', interval: 133 },
            { name: '青锋急急如律令 Blade Abracadabra', singer: 'HOYO-MiX', mid: '002YRR1M3qUQhN', interval: 107 },
            { name: '鹤唳 Into the Desolate', singer: 'HOYO-MiX', mid: '0007XB2r0PqplS', interval: 124 },
            { name: '逐鹿 Deerstalker', singer: 'HOYO-MiX', mid: '002DCxNk1iQkes', interval: 113 },
            { name: '浮槎竟天 Skyedge Voyage', singer: 'HOYO-MiX', mid: '0028zkA00TB01x', interval: 123 },
            { name: '坎离交济 Severed Harmony', singer: 'HOYO-MiX', mid: '001zHF2u1kAC5n', interval: 124 },
            { name: '无俗念 Terrene Deliverance', singer: 'HOYO-MiX', mid: '001ruWg03WXAeL', interval: 121 },
            { name: '逍遥游 Serene Stroll', singer: 'HOYO-MiX', mid: '003YEaJ94P1F4o', interval: 82 },
            { name: '烟霞逝梦 Evanescent Dreams', singer: 'HOYO-MiX', mid: '001aNPPV13MnON', interval: 114 },
            { name: '解脱妙谛 Mokshasatya', singer: 'HOYO-MiX', mid: '001mUwjG1FFOIP', interval: 113 },
            { name: '药王救世陀罗尼 Sanctus Medicus Dharani', singer: 'HOYO-MiX', mid: '001stHzU21HPJs', interval: 93 },
            { name: '金鼎折足 A Brew of Storm', singer: 'HOYO-MiX', mid: '000fy63X2R0FE7', interval: 123 },
            { name: '弹铗飞光现龙影 Gleaming Clash', singer: 'HOYO-MiX', mid: '003jusbI3OrLkD', interval: 78 },
            { name: '古海宫墟 Erstwhile Resonance', singer: 'HOYO-MiX', mid: '001pu3yE3PtCPA', interval: 128 },
            { name: '海若隐珠 Obscured Pearls', singer: 'HOYO-MiX', mid: '003jFGoR1HZW1S', interval: 135 },
            { name: '玄牝之门,万类之根 Arteria Inceptionis', singer: 'HOYO-MiX', mid: '000vuWJa3zqMgK', interval: 123 },
            { name: '蝉喓歌·晦明苦短 Pedujara: Ephemeral Cycle', singer: 'HOYO-MiX', mid: '001FRTeP2k8UNs', interval: 120 },
            { name: '蝉喓歌·仙骸有终 Pedujara: Even Immortality Ends', singer: 'HOYO-MiX', mid: '001zHAxB0nS7pY', interval: 124 },
            { name: '蝉喓歌·长命无绝 Pedujara: Demiseless Existence', singer: 'HOYO-MiX', mid: '004avuty2xznZc', interval: 123 },
            { name: '载歌须纵酒 Paean of Indulgence', singer: 'HOYO-MiX', mid: '004c8a4P1fauXl', interval: 122 },
            { name: '夜市灯如昼 Night Bazaar in Full Glow', singer: 'HOYO-MiX', mid: '001KRyzE2wXhHw', interval: 116 },
            { name: '稇载待启程 Whispers of Departure', singer: 'HOYO-MiX', mid: '000S1Wec4GP3SH', interval: 96 },
            { name: '合巹记 Wedding Wine', singer: 'HOYO-MiX', mid: '0024ASdl1HFmKf', interval: 55 },
            { name: '眠鸥宿鹭 Nesting Avians', singer: 'HOYO-MiX', mid: '002hBGFy0mQChL', interval: 110 },
            { name: '鸥鹭忘机 Above The Fray', singer: 'HOYO-MiX', mid: '002rUoVz4dWQCs', interval: 107 },
            { name: '鸮啼鬼啸 Haunting Hoots', singer: 'HOYO-MiX', mid: '0008XMNU2GMZzK', interval: 126 },
            { name: '百鬼率舞 Dancing Fantasms', singer: 'HOYO-MiX', mid: '003p1YEj252Wih', interval: 91 },
            { name: '初花学剑动星芒 My Sword Stirs Starlight', singer: 'HOYO-MiX', mid: '000xMJOI0gtb0q', interval: 106 },
            { name: '此身堕泥犁 To Naraka We Sink', singer: 'HOYO-MiX', mid: '003okStI32zQLH', interval: 117 },
            { name: '八寒阴狱 Eight Great Cold Hells', singer: 'HOYO-MiX', mid: '002MVy3A3rn9bT', interval: 114 },
            { name: '啸月狼奔 Moonhowl Stampede', singer: 'HOYO-MiX', mid: '003xNscf3oInD8', interval: 97 },
            { name: '生苦不绝，烦漏难尽 Life\'s Suffering, An Endless Tide', singer: 'HOYO-MiX', mid: '000lO9BR255wFr', interval: 102 },
            { name: '云间游 Cloudwide Voyage', singer: 'HOYO-MiX', mid: '003OzK0K0fmaS6', interval: 116 },
            { name: '且挽心月作弧弓 With My Heartstring as Bow', singer: 'HOYO-MiX', mid: '0033XlS81uDPzX', interval: 136 },
            { name: '天霄登临 Welkin\'s Advent', singer: 'HOYO-MiX', mid: '001e4zaF01tT0V', interval: 99 },
            { name: '撄锋竞武 A Duel of Connecting Blades', singer: 'HOYO-MiX', mid: '003yIuAu0gQ8Zf', interval: 112 },
            { name: '剑葬生死斗 Fatal Clash of Swordgraves', singer: 'HOYO-MiX', mid: '001JhCod1cM0PV', interval: 111 },
            { name: '心兽灭却 Inner Beast Vanquished', singer: 'HOYO-MiX', mid: '003r0F2m2m00Dk', interval: 117 },
            { name: '天下少年第一流 The Epitome of Young Morals', singer: 'HOYO-MiX', mid: '0002H3Df4KOol9', interval: 87 }
        ]
    },
    {
        name: '匹诺康尼',
        icon: '🕰️',
        songs: [
            { name: '不眠之夜', singer: '张杰 / HOYO-MiX', mid: '0032wpIs0D30HZ', interval: 138 },
            { name: '欢迎来到美梦小镇！Part.1 Welcome to Dreamville!', singer: 'HOYO-MiX', mid: '001Vt3D82A1eVh', interval: 108 },
            { name: '欢迎来到美梦小镇！Part.2 Welcome to Dreamville!', singer: 'HOYO-MiX', mid: '002w2Bum3Y9El0', interval: 83 },
            { name: '欢迎来到美梦小镇！Part.3 Welcome to Dreamville!', singer: 'HOYO-MiX', mid: '0027y1Xg4Eg1Vh', interval: 87 },
            { name: '尘世乐园 This Side of Paradise', singer: 'HOYO-MiX', mid: '000Fefg616gqXN', interval: 123 },
            { name: '倒扣的王牌 Ace in the Hole', singer: 'HOYO-MiX', mid: '0017iAy84U1IOW', interval: 122 },
            { name: '嗨，多莉！ Hi, Dolly!', singer: 'HOYO-MiX', mid: '002gZTEf295B6r', interval: 78 },
            { name: '黄金之地 Golden Land', singer: 'HOYO-MiX', mid: '001SZO8E0YEYBe', interval: 120 },
            { name: '长眠不醒 The Big Sleep', singer: 'HOYO-MiX', mid: '002Esiot0RwUde', interval: 128 },
            { name: '梦客漫步 Dreamwalker', singer: 'HOYO-MiX', mid: '001a0GSm3OdICD', interval: 101 },
            { name: '另一方玩家 The Player on the Other Side', singer: 'HOYO-MiX', mid: '000h78mI0BmrPQ', interval: 111 },
            { name: '公平游戏 Fair Play', singer: 'HOYO-MiX', mid: '002Bk5JP39lATe', interval: 104 },
            { name: '假如醒于午夜 If One Wakes at Midnight', singer: 'HOYO-MiX', mid: '001hkZWc0PmcKv', interval: 60 },
            { name: '现实原则 Realitätsprinzip', singer: 'HOYO-MiX', mid: '0024dYcR2DMQzW', interval: 142 },
            { name: '快乐原则 Lustprinzip', singer: 'HOYO-MiX', mid: '002p2RDh3SkZb7', interval: 106 },
            { name: '抵抗白昼 Against the Day', singer: 'HOYO-MiX', mid: '001k7Rd64VBz3Z', interval: 117 },
            { name: '挑战读者 Challenge to the Reader', singer: 'HOYO-MiX', mid: '001PLwqr2snoph', interval: 105 },
            { name: '清醒梦 Lucid Dreams', singer: 'HOYO-MiX', mid: '002z5S3c13T9Qn', interval: 71 },
            { name: '半途之屋 Halfway House', singer: 'HOYO-MiX', mid: '001E06Lb0faDBS', interval: 119 },
            { name: '满堂彩 Full House', singer: 'HOYO-MiX', mid: '000VzH9e0CsPW5', interval: 48 },
            { name: '午夜特快 The Midnight Special', singer: 'HOYO-MiX', mid: '001aJr2d0GyUVL', interval: 82 },
            { name: '意乱情迷 Spellbound', singer: 'HOYO-MiX', mid: '003KE1vg2Cjj83', interval: 73 },
            { name: '山巅之城 City upon a Hill', singer: 'HOYO-MiX', mid: '002ZDeof36DwHi', interval: 96 },
            { name: '愚者总按两遍铃 The Fool Always Rings Twice', singer: 'HOYO-MiX', mid: '004HL2fH2wAC5J', interval: 91 },
            { name: '落水狗 Wet Dog', singer: 'HOYO-MiX', mid: '000lGzxL2cKWw2', interval: 82 },
            { name: '隐性梦境 Latent Content of Dream', singer: 'HOYO-MiX', mid: '003BXjIz4EMGzV', interval: 122 },
            { name: '关于记忆永恒的解构 On the Disintegration of Evermemoria', singer: 'HOYO-MiX', mid: '000sImx40hFNfy', interval: 66 },
            { name: '公民哈努努 Citizen Hanunu', singer: 'HOYO-MiX', mid: '003LWSnL2OfyRx', interval: 76 },
            { name: '显性梦境 Manifest Content of Dream', singer: 'HOYO-MiX', mid: '004bU7En3XARMK', interval: 92 },
            { name: '能指链条 Chaîne Signifiante', singer: 'HOYO-MiX', mid: '0043O9si2kMQZ4', interval: 103 },
            { name: '镜像阶段 Stade du Miroir', singer: 'HOYO-MiX', mid: '002pkVrY3igGeu', interval: 95 },
            { name: '死亡欲力 Todestrieb', singer: 'HOYO-MiX', mid: '003Mnf113SKIAp', interval: 29 },
            { name: '无人生还 Return of None', singer: 'HOYO-MiX', mid: '0036Mhyo1NWkUt', interval: 121 },
            { name: '渡鸦言曰 Quoth the raven', singer: 'HOYO-MiX', mid: '003mjJrL43nz86', interval: 155 },
            { name: '永不复焉 Nevermore', singer: 'HOYO-MiX', mid: '000osf171PJ2Hj', interval: 121 },
            { name: '美梦第一！ Dream First!', singer: 'HOYO-MiX', mid: '000vyIbw2QxwTS', interval: 94 },
            { name: '缄默法则 Omertà', singer: 'HOYO-MiX', mid: '000H99hT1roP3d', interval: 91 },
            { name: '飞毛腿哈姆兹 Speedy Hamz', singer: 'HOYO-MiX', mid: '003TSfJW2Tq8Xc', interval: 66 },
            { name: '懦夫博弈 The Game of Chicken', singer: 'HOYO-MiX', mid: '002yqNIf1Xrtej', interval: 91 },
            { name: '宁入地狱，而非虚无 Hell Is Preferable to Nihility', singer: 'HOYO-MiX', mid: '001fjyHl0Megsy', interval: 99 },
            { name: '惟无常恒驻留 Nought May Endure But Mutability', singer: 'HOYO-MiX', mid: '003RfrrI0lzBTT', interval: 108 },
            { name: '北极星 Polaris', singer: 'HOYO-MiX', mid: '002aTBfC0uvk9T', interval: 123 },
            { name: '常夜航标 Lodestar in Evernight', singer: 'HOYO-MiX', mid: '004GKeMc0s5yzi', interval: 146 },
            { name: '乐园陌影 Strranger Than Paradise', singer: 'HOYO-MiX', mid: '004cpFC80ymg5Y', interval: 181 },
            { name: '邻间的骰子之舞 The Dice in the Other Room', singer: 'HOYO-MiX', mid: '002D3iiv4b0zH0', interval: 62 },
            { name: '速度与坚果 Fast & Furynuts', singer: 'HOYO-MiX', mid: '002JIZtw1xsYbS', interval: 60 },
            { name: '坠入裂土 Into the Cracked Earth', singer: 'HOYO-MiX', mid: '001BqGlh1mhLXS', interval: 105 },
            { name: '海中之城 The City in the Sea', singer: 'HOYO-MiX', mid: '002X4eA64Bfuwh', interval: 102 },
            { name: '星海浮沉录 A Star Is Born', singer: 'HOYO-MiX', mid: '004CjUHD20kBG3', interval: 184 },
            { name: '演员的自我修养 An Actor Prepares', singer: 'HOYO-MiX', mid: '004RAj1s3gSZSX', interval: 112 },
            { name: '小小凯撒 Little Little Caesar', singer: 'HOYO-MiX', mid: '003XmTlR1EnC6Y', interval: 97 },
            { name: '时间的高贵 Nobility of Time', singer: 'HOYO-MiX', mid: '000yaS0X0L67Si', interval: 117 },
            { name: '热情如火 Some Like It Hot', singer: 'HOYO-MiX', mid: '000Mdj0n0Ak6Wr', interval: 99 },
            { name: '娱乐至上 No Business Like Show Business', singer: 'HOYO-MiX', mid: '004eLuxo1DKOTX', interval: 71 },
            { name: '星光大道 Walk of Fame', singer: 'HOYO-MiX', mid: '000kAKzZ1ruozs', interval: 86 },
            { name: '笼中鸟 Caged Wings', singer: 'HOYO-MiX', mid: '004Afp7l0MTkjf', interval: 103 },
            { name: '空虚荒芜是那大海 Od\' und leer das Meer', singer: 'HOYO-MiX', mid: '004Z6s9N2GfBse', interval: 280 },
            { name: '昔在、今在、永在的剧目 The Past, Present, and Eternal Show', singer: 'HOYO-MiX', mid: '004YbbGv0nveRC', interval: 101 },
            { name: '律是罪的权势 The Strength of Sin Is the Law', singer: 'HOYO-MiX', mid: '001FHBQS1sw6XF', interval: 114 },
            { name: '罪是死的毒钩 The Sting of Death Is Sin', singer: 'HOYO-MiX', mid: '002yqvtQ35BsT2', interval: 115 },
            { name: '太初有道 Im Anfang war das Wort', singer: 'HOYO-MiX', mid: '002apBPU3tCVXz', interval: 102 },
            { name: '恶徒蒙召受判 Confutatis', singer: 'HOYO-MiX', mid: '003tDQG24ekhMW', interval: 82 },
            { name: '义人如羊走迷 Agnus Aeon', singer: 'HOYO-MiX', mid: '001qgTUf107GmV', interval: 100 },
            { name: '生灵永恒安息 Requiem Aeternam', singer: 'HOYO-MiX', mid: '0016UMh51JmQLh', interval: 112 },
            { name: '天光永恒照耀 Lux Aterna', singer: 'HOYO-MiX', mid: '004WwFMm054cK1', interval: 136 },
            { name: '欢呼响彻云霄 Hosanna in Excelsis', singer: 'HOYO-MiX', mid: '002nrViM1Xhuqw', interval: 105 },
            { name: '坚我苦弱血肉 Infirma Nostri Corporis', singer: 'HOYO-MiX', mid: '003SdQrQ3eJv8E', interval: 117 },
            { name: '第八交响曲「千日同升」 Symphony No.8 "A Thousand Suns"', singer: 'HOYO-MiX', mid: '002WG3Oq1OcIYZ', interval: 136 },
            { name: '睡蕉之歌', singer: 'HOYO-MiX', mid: '000J792w13DNCP', interval: 17 },
            { name: '睡蕉之歌（伴奏）', singer: 'HOYO-MiX', mid: '0031LmTf4KmZZj', interval: 17 },
            { name: '群像戏 Ensemble Cast', singer: 'HOYO-MiX', mid: '001eip7d1cYehT', interval: 62 },
            { name: '私人时间 Alone Time', singer: 'HOYO-MiX', mid: '003vHnb34CDTmA', interval: 128 },
            { name: '扬帆 Now, Voyager', singer: 'HOYO-MiX', mid: '0040lWhI2Zt2gc', interval: 128 },
            { name: '无神论者的弥撒 La Messe de l\'athée', singer: 'HOYO-MiX', mid: '003MGT9G1GT4Ka', interval: 96 },
            { name: '美梦多彩 Color Your Dreams', singer: 'HOYO-MiX', mid: '002XvNuF3evmY3', interval: 95 },
            { name: '在黄昏起飞 Takeoff at Dusk', singer: 'HOYO-MiX', mid: '001VDCXH155xHX', interval: 99 },
            { name: '梦泡漂流 Dream Drifting', singer: 'HOYO-MiX', mid: '003sNKJD2cmuak', interval: 113 },
            { name: '失眠症 Dance in a Deep Dream', singer: 'HOYO-MiX', mid: '001viKrW3nev5H', interval: 62 },
            { name: '倒转的时刻 Reversed Moments', singer: 'HOYO-MiX', mid: '001BhClt29zcju', interval: 100 },
            { name: '漂浮节奏 Floating Tempo', singer: 'HOYO-MiX', mid: '002QuyIc0lOm70', interval: 73 },
            { name: '漫无止境 Up to This', singer: 'HOYO-MiX', mid: '0010QSU00bCmle', interval: 50 },
            { name: '音律绚烂 Melody of Dazzling Light', singer: 'HOYO-MiX', mid: '003dKplq2eL1Qq', interval: 80 },
            { name: '正义的伙伴 Hero of Justice', singer: 'HOYO-MiX', mid: '000mBG7l2yXdbs', interval: 95 },
            { name: '圣杯之夜 Night of the Holy Grail', singer: 'HOYO-MiX', mid: '002NYxIV0rg4HO', interval: 92 },
            { name: '理想乡 Utopia', singer: 'HOYO-MiX', mid: '000ZtvC70lzar5', interval: 105 },
            { name: '唯有胜利 Victory Above All', singer: 'HOYO-MiX', mid: '003TTY3z3XIfmt', interval: 93 },
            { name: '刺破黑暗 Pierce the Darkness', singer: 'HOYO-MiX', mid: '001RyOJJ3cS845', interval: 58 },
            { name: '愿风与你相伴 The Wind Be With You', singer: 'HOYO-MiX', mid: '004QSK7509wlXm', interval: 64 },
            { name: '振翅 Wingflap', singer: 'HOYO-MiX', mid: '003Gxu6B3imU9b', interval: 75 },
            { name: '忆梦浮廊 Corridor of Memorial Dreams', singer: 'HOYO-MiX', mid: '003vqpGS1m4syw', interval: 114 },
            { name: '神降 Theophany', singer: 'HOYO-MiX', mid: '003c9PTl2IGt6I', interval: 117 },
            { name: '鸣蛀之梦 Dream of Gnawing', singer: 'HOYO-MiX', mid: '003CE1uI3KjZsp', interval: 124 },
            { name: '虚空漫步 Void Walk', singer: 'HOYO-MiX', mid: '0011swC01SpA5C', interval: 94 },
            { name: '深魇噩兆 Nightmarish Omen', singer: 'HOYO-MiX', mid: '001YWkyf1lXX6x', interval: 107 }
        ]
    },
    {
        name: '翁法罗斯',
        icon: '🏛️',
        songs: [
            { name: '何者', singer: '谭晶 / HOYO-MiX', mid: '003YIetk4CRlfq', interval: 146 },
            { name: 'Nameless Faces', singer: '幾田りら / HOYO-MiX', mid: '001oPDRi2cBvkE', interval: 146 },
            { name: '何者 (伴奏)', singer: 'HOYO-MiX', mid: '003afWoF1cBFPt', interval: 146 },
            { name: '拂晓 Proi Proi', singer: 'HOYO-MiX / NIDA', mid: '000J0KtD2auL4h', interval: 238 },
            { name: '深黑蔓延时 When Darkness Spreads', singer: 'HOYO-MiX', mid: '001gZQO64Wux4F', interval: 118 },
            { name: '打碎神的冠冕 Shatter the God\'s Crown', singer: 'HOYO-MiX', mid: '001NFe0T3JbgIX', interval: 114 },
            { name: '致世界 To the World', singer: 'HOYO-MiX', mid: '000UoskF1j4f9R', interval: 116 },
            { name: '世代的颂歌 Anthem of Eras', singer: 'HOYO-MiX', mid: '001tIrHe2qXZ4K', interval: 153 },
            { name: '黎明座下 Under the Seat of Dawn', singer: 'HOYO-MiX', mid: '004Bkz1i38mLPK', interval: 145 },
            { name: '金血的战曲 Battle Hymn of the Golden Blood', singer: 'HOYO-MiX', mid: '0020W0gD1HKt91', interval: 129 },
            { name: '波涛舞会 Promenade of Tides', singer: 'HOYO-MiX', mid: '0037JjDB2n9R9t', interval: 117 },
            { name: '活火 Living Flame', singer: 'HOYO-MiX', mid: '000mVkD10drcUE', interval: 94 },
            { name: '伐神 Theomakhia', singer: 'HOYO-MiX', mid: '000L7tOK1PJrqr', interval: 99 },
            { name: '游叙草木 Plantlife Euthys', singer: 'HOYO-MiX', mid: '003KHIMw1iYrDh', interval: 117 },
            { name: '翻飞之间 Between Whims', singer: 'HOYO-MiX', mid: '003HBQl60wu8V4', interval: 100 },
            { name: '大地牧歌 The Pastoral of the Lands', singer: 'HOYO-MiX', mid: '000xCZro3FHEZl', interval: 48 },
            { name: '驻留的游谣 Wandering Rhymes', singer: 'HOYO-MiX', mid: '001ZdbcL1U8wE7', interval: 114 },
            { name: '命运之轮 Wheel of Fate', singer: 'HOYO-MiX', mid: '001PBqU54Ny0ZD', interval: 147 },
            { name: '求谕 In Search of Prophecy', singer: 'HOYO-MiX', mid: '004JzzPn4WAmIw', interval: 147 },
            { name: '诸神的回响 Echoes of the Divine', singer: 'HOYO-MiX', mid: '002GiB6M2hiMDd', interval: 110 },
            { name: '被践踏的蛇 Trampled Snake', singer: 'HOYO-MiX', mid: '003pAc3Y0Ol66i', interval: 97 },
            { name: '葡萄树和山羊 Grapevine and Mountain Goat', singer: 'HOYO-MiX', mid: '003nTsmN07iXV2', interval: 93 },
            { name: '预言的浅吟 Whisper of Prophecy', singer: 'HOYO-MiX', mid: '0008rr5U3yt3iB', interval: 103 },
            { name: '如谁所书 As Written By Whom', singer: 'HOYO-MiX', mid: '0011c7hH0c93fK', interval: 114 },
            { name: '祈留无路 Prayer for Pathlessness', singer: 'HOYO-MiX', mid: '000O5ccO3R527c', interval: 90 },
            { name: '长昼的絮语 Whispers of Day', singer: 'HOYO-MiX', mid: '002RRnCO1SFfUR', interval: 125 },
            { name: '帷幕之中 Within the Veil', singer: 'HOYO-MiX', mid: '004Avouc2fnwqG', interval: 96 },
            { name: '谕声的薄音 Fading Prophecy', singer: 'HOYO-MiX', mid: '002lm0Zl3bYtIB', interval: 98 },
            { name: '忆河的织者 Weaver of Memories', singer: 'HOYO-MiX', mid: '003YTx691lZvVp', interval: 103 },
            { name: '噤声之弦 Silent Strings', singer: 'HOYO-MiX', mid: '001LnyFr1RHO8A', interval: 72 },
            { name: '起初和终结 Origin and Finale', singer: 'HOYO-MiX', mid: '003Oi20Z3IGKi7', interval: 155 },
            { name: '碑文落处 Where The Inscription Was', singer: 'HOYO-MiX', mid: '003lSikI36OAda', interval: 102 },
            { name: '荣耀不死 Undying Glory', singer: 'HOYO-MiX', mid: '001787Qt3YjVdN', interval: 137 },
            { name: '营火未熄 The Eternal Campflame', singer: 'HOYO-MiX', mid: '002rtjaP0ac0w2', interval: 170 },
            { name: '烽烟余味 Beacon Smoke Residue', singer: 'HOYO-MiX', mid: '00116jZD43Qbmu', interval: 130 },
            { name: '长夜斧声 Axe of Evernight', singer: 'HOYO-MiX', mid: '002MR8G84YSegm', interval: 166 },
            { name: '致歌耳戈 To Gorgo', singer: 'HOYO-MiX', mid: '001IZvQ93K6pLl', interval: 128 },
            { name: '致纷争的一切 To All Things Strifeful', singer: 'HOYO-MiX', mid: '0033841N0PrZyf', interval: 102 },
            { name: '万有之王父 King Father of All', singer: 'HOYO-MiX', mid: '000GmGjL2SXln5', interval: 114 },
            { name: '触及残刃 Touch of the Broken Blade', singer: 'HOYO-MiX', mid: '000qq5bm0xihy5', interval: 120 },
            { name: '狩猎神明 A Hunt for the Divine', singer: 'HOYO-MiX', mid: '000zSvaU1s1AVs', interval: 112 },
            { name: '苍翠识海 Verdant Sea of Knowing', singer: 'HOYO-MiX', mid: '004fMhFb0MJXpu', interval: 101 },
            { name: '破碎凡界 Shattered Mortal Realms', singer: 'HOYO-MiX', mid: '003IdYe51D8S1l', interval: 100 },
            { name: '散佚书卷 Scattered Manuscripts', singer: 'HOYO-MiX', mid: '003YFIIn1ek0nE', interval: 98 },
            { name: '理性的薄暮 Dusk of Rationality', singer: 'HOYO-MiX', mid: '003yeU413l5UKA', interval: 78 },
            { name: '步入凝重 Unto Dignity', singer: 'HOYO-MiX', mid: '004d38uL1KvrI0', interval: 109 },
            { name: '致记忆 To Remembrance', singer: 'HOYO-MiX', mid: '002XE6Dv3phvIa', interval: 32 },
            { name: '门径小夜曲 Serenade of the Passage', singer: 'HOYO-MiX', mid: '004J0CRy4Ln9XP', interval: 52 },
            { name: '温暖的匣盒 Warmth Contained', singer: 'HOYO-MiX', mid: '001OA8iD2riM0A', interval: 119 },
            { name: '故事与甜饼 Stories and Sweets', singer: 'HOYO-MiX', mid: '003l6zaG0U4CNK', interval: 116 },
            { name: '干涩的匣盒 Dryness Caged', singer: 'HOYO-MiX', mid: '00411a0r4COxTD', interval: 96 },
            { name: '于明日怀中 In the Arms of Tomorrow', singer: 'HOYO-MiX', mid: '000nLK6f10hDTQ', interval: 120 },
            { name: '羊皮下 Beneath the Sheep\'s Skin', singer: 'HOYO-MiX', mid: '001E3f7w3MTG5g', interval: 103 },
            { name: '赐予纷争 Gift of Strife', singer: 'HOYO-MiX', mid: '000koEUN1wOyr5', interval: 74 },
            { name: '代冠 Coronation', singer: 'HOYO-MiX', mid: '0043y2dl0P4N1k', interval: 53 },
            { name: '醒锋 The Edge Awakened', singer: 'HOYO-MiX', mid: '003ctjG54Xp0LP', interval: 100 },
            { name: '吐露的游谣 Ballad of Revelations', singer: 'HOYO-MiX', mid: '001ciq3N28HGG3', interval: 110 },
            { name: '黎明颂歌 Hymn of Dawn', singer: 'HOYO-MiX', mid: '0038TSFY2BcyP0', interval: 115 },
            { name: '昏崖咏叹 Aria of the Precipice', singer: 'HOYO-MiX', mid: '000w8ZDu427KCE', interval: 124 },
            { name: '求索神性 Seeker of Divinity', singer: 'HOYO-MiX', mid: '001TiiJv20JnPy', interval: 125 },
            { name: '云崖无晖 Lightless Dawncloud', singer: 'HOYO-MiX', mid: '003djq2z3gXYlp', interval: 119 },
            { name: '冥流低韵 Rhyme of the Stream of Souls', singer: 'HOYO-MiX', mid: '001mR0EQ1jRB32', interval: 115 },
            { name: '冥流哀诗 Lament on Stream of Souls', singer: 'HOYO-MiX', mid: '003wjm4E47P7vU', interval: 112 },
            { name: '寂暗长阶 Long Strides of Silence', singer: 'HOYO-MiX', mid: '001shvRB2CRRLV', interval: 113 },
            { name: '黄金 Chrysos', singer: 'HOYO-MiX', mid: '000rUknd2mk3Ac', interval: 56 },
            { name: '复抵初识 Back to the Start', singer: 'HOYO-MiX', mid: '000z3Cjr4frrEE', interval: 112 },
            { name: '死龙挽歌 Elegy of Netherwing', singer: 'HOYO-MiX', mid: '003w8ojY3qOhb1', interval: 123 },
            { name: '安提灵花语 Antila Floriography', singer: 'HOYO-MiX', mid: '000HwO99081TDJ', interval: 115 },
            { name: '赠予一瞬 A Moment to Offer', singer: 'HOYO-MiX', mid: '002Gt5fp24U0Wd', interval: 133 },
            { name: '殇默的游谣 Ballad of Silence', singer: 'HOYO-MiX', mid: '003upmJH2Pg2Pp', interval: 80 },
            { name: '播种龙牙 Sowing of the Dragon\'s Fangs', singer: 'HOYO-MiX', mid: '004GJiFv0vBKG6', interval: 110 },
            { name: '幕起与幕落 Curtain Rise, Curtain Fall', singer: 'HOYO-MiX', mid: '004LzTXT4P5bw7', interval: 154 },
            { name: '圣城夕照 Holy City\'s Twilight', singer: 'HOYO-MiX', mid: '000tNEZL4ZrYYv', interval: 116 },
            { name: '祈望的游谣 Ballad of Hope', singer: 'HOYO-MiX', mid: '000yCqtM4CxOMV', interval: 82 },
            { name: '追袭即兴诗 Spontaneous Poetry', singer: 'HOYO-MiX', mid: '003aGWZo2My0oU', interval: 110 },
            { name: '置于身前 What Lies Before', singer: 'HOYO-MiX', mid: '0033pMp338aWXk', interval: 116 },
            { name: '字文纷飞间 Between the Text', singer: 'HOYO-MiX', mid: '003eYYKk1D9KE5', interval: 106 },
            { name: '幽冥挽调 Elegy of the Nether', singer: 'HOYO-MiX', mid: '003OfL4e1gy40Y', interval: 115 },
            { name: '新页 New Page', singer: 'HOYO-MiX', mid: '0021xfAA1b7rJL', interval: 46 },
            { name: '踏足无垠 Boundless Strides', singer: 'HOYO-MiX', mid: '000eb0yh34Ipk0', interval: 207 },
            { name: '追觅阴云 Gloomseeker', singer: 'HOYO-MiX', mid: '002X9n6k2xVkj3', interval: 109 },
            { name: '云雪的叙歌 Narration of Clouds and Snow', singer: 'HOYO-MiX', mid: '001HT7zR1Sh8Wg', interval: 93 },
            { name: '阳雷的骤曲 Daythunder Rhapsody', singer: 'HOYO-MiX', mid: '000VeLTJ0yR1sk', interval: 102 },
            { name: '霆间穿行 Passing of Thunder', singer: 'HOYO-MiX', mid: '003YXk3b1n7MJE', interval: 123 },
            { name: '斫日 Sunslayer', singer: 'HOYO-MiX', mid: '001F9fnc2eu0mk', interval: 102 },
            { name: '折翼的耀斑 Solar Flare of Broken Wings', singer: 'HOYO-MiX', mid: '002v92sa3O3ez2', interval: 140 },
            { name: '尘晖余迹 Afterglow in Dust', singer: 'HOYO-MiX', mid: '0041t2uT0sqD9k', interval: 114 },
            { name: '拂晓 Proi Proi (伴奏)', singer: 'HOYO-MiX', mid: '004Fnrzb2vPzH3', interval: 238 },
            { name: 'NAME == 隐德来希 NAME == Entelechy', singer: 'HOYO-MiX', mid: '003oOscO2APco2', interval: 205 },
            { name: '迷境 Maze', singer: 'HOYO-MiX', mid: '001sRT843wxGaO', interval: 123 },
            { name: '故乡 Homeland', singer: 'HOYO-MiX', mid: '001kxJ3739FlnJ', interval: 120 },
            { name: '秘榭曲谣 Elysiae Melody', singer: 'HOYO-MiX', mid: '004V7nfw3ElROg', interval: 119 },
            { name: '讴歌苍翠 Ode of the Verdant', singer: 'HOYO-MiX', mid: '0009Go5K2OZOLX', interval: 136 },
            { name: '圣林 Sacred Grove', singer: 'HOYO-MiX', mid: '001gH8wo0QLxNO', interval: 103 },
            { name: '明日之约 Promise of Tomorrow', singer: 'HOYO-MiX', mid: '001e1tes1zVjnr', interval: 126 },
            { name: '凄焰 Infernal Blaze', singer: 'HOYO-MiX', mid: '0044YWDa0MEteB', interval: 111 },
            { name: '风仍温暖时 When The Wind Was Warm', singer: 'HOYO-MiX', mid: '002qMEBs0kQgM2', interval: 133 },
            { name: '泡沫之下 Beneath the Bubbles', singer: 'HOYO-MiX', mid: '000VK5ep45dh5i', interval: 124 },
            { name: '凝固的浪花 Frozen Tides', singer: 'HOYO-MiX', mid: '003IIOBL0XhRc0', interval: 111 },
            { name: '洄游的希望 Migratory Hope', singer: 'HOYO-MiX', mid: '004a0wGA2oZYz4', interval: 56 },
            { name: '酣生梦宴 Sweet Dreams and Feasts', singer: 'HOYO-MiX', mid: '000D6Tb82mbD5q', interval: 130 },
            { name: '帷幕视窗 The Looming Curtains', singer: 'HOYO-MiX', mid: '004Mxxzt23LvQI', interval: 100 },
            { name: '为往昔而行 A Journey for the Past', singer: 'HOYO-MiX', mid: '000Krq164UvNvT', interval: 81 },
            { name: '陌颜之人 Face of a Stranger', singer: 'HOYO-MiX', mid: '003gyBzj0MB7mh', interval: 117 },
            { name: '路漫长夜 The Long Road Through Evernight', singer: 'HOYO-MiX', mid: '0023Ac014ZhbtF', interval: 106 },
            { name: '火尽薪传 Passing the Torch', singer: 'HOYO-MiX', mid: '002B0OlZ4ddB0D', interval: 130 },
            { name: '征服者的思忖 Conqueror\'s Contemplation', singer: 'HOYO-MiX', mid: '001WE23s4diU7L', interval: 106 },
            { name: '微光小调 Starlight Serenade', singer: 'HOYO-MiX', mid: '003nJsup1fYV3n', interval: 32 },
            { name: '第十三矢量 Vector Thirteen', singer: 'HOYO-MiX', mid: '002biVlY3NYK6o', interval: 99 },
            { name: '矩阵 Matrix', singer: 'HOYO-MiX', mid: '001udlX84BZ83q', interval: 136 },
            { name: '神话公理 Mythical Axiom', singer: 'HOYO-MiX', mid: '0020kOj53hkxB9', interval: 190 },
            { name: '缓冲区 Buffer Zone', singer: 'HOYO-MiX', mid: '0007Nb4n1aOzS8', interval: 85 },
            { name: '流溢中枢 Overflowing Core', singer: 'HOYO-MiX', mid: '004Yt8891jwZi0', interval: 117 },
            { name: '缔造明日 Forging Tomorrow', singer: 'HOYO-MiX', mid: '003NTWBF4W4j1e', interval: 112 },
            { name: '流淌的思念 Flowing Memories', singer: 'HOYO-MiX', mid: '002oEe3k18VPCM', interval: 130 },
            { name: '不洁之血 Unholy Blood', singer: 'HOYO-MiX', mid: '000HSCfi0PTwkO', interval: 115 },
            { name: '相位偏移 Phase Shift', singer: 'HOYO-MiX', mid: '002WlXIK1RmCDg', interval: 102 },
            { name: '失速飞行 Stalled Flight', singer: 'HOYO-MiX', mid: '00017Tr53EX23n', interval: 95 },
            { name: '宁神长梦 Tranquil Dream', singer: 'HOYO-MiX', mid: '001UEh052SOOMp', interval: 123 },
            { name: '无名的疗愈 Nameless Healing', singer: 'HOYO-MiX', mid: '001ZAn4F0LBkT6', interval: 44 },
            { name: '心灵 Mind and Soul', singer: 'HOYO-MiX', mid: '004dY05604Q2uj', interval: 81 },
            { name: '以全世之名 In the Name of All Worlds', singer: 'HOYO-MiX', mid: '000d9t4s2bjXTK', interval: 76 },
            { name: '心忆 Remembrance of the Heart', singer: 'HOYO-MiX', mid: '004V05Eo1KKHh8', interval: 218 },
            { name: '时隙攻防 Clash of Time Rift', singer: 'HOYO-MiX', mid: '004SwdD74CQCmg', interval: 95 },
            { name: '龙鸣霄壤 Echoes of Dragon', singer: 'HOYO-MiX', mid: '002skLf50Akr0f', interval: 89 },
            { name: '无瑕金血 Flawless Ichor', singer: 'HOYO-MiX', mid: '002W1Rmd1XIKcx', interval: 82 },
            { name: '黄金色祝愿 Golden Desires', singer: 'HOYO-MiX', mid: '003uUaQA2BG1y9', interval: 110 },
            { name: '神祇的终点 The End of Gods', singer: 'HOYO-MiX', mid: '002Xm94F15ow2G', interval: 156 },
            { name: '病毒 Virus', singer: 'HOYO-MiX', mid: '000pTQdn1F35oA', interval: 104 },
            { name: '蜃楼 Mirage', singer: 'HOYO-MiX', mid: '002YdWxZ1nuckg', interval: 97 },
            { name: '遗恨蜃景 Mirage of Regrets', singer: 'HOYO-MiX', mid: '004biPzg25Zz8y', interval: 209 },
            { name: '剑冢 Tomb of Blades', singer: 'HOYO-MiX', mid: '002rdfJn328Efc', interval: 185 },
            { name: '烧尽神国之火 Immolation of the Heavens', singer: 'HOYO-MiX', mid: '001ienZU09B67A', interval: 129 },
            { name: '苦难汇聚成河 Agony Converging into River', singer: 'HOYO-MiX', mid: '001df1cx1rp9X4', interval: 170 },
            { name: '一页永恒 An Eternal Page', singer: 'HOYO-MiX', mid: '002SowLz0t6Wgo', interval: 196 },
            { name: '深爱的世界 A World of Deep Love', singer: 'HOYO-MiX', mid: '003b9aDN4XsQLx', interval: 190 },
            { name: '再创世 Era Nova', singer: 'HOYO-MiX', mid: '001bWAdc0gCGOs', interval: 68 },
            { name: '阳光与汗水 Sweat and Sunshine', singer: 'HOYO-MiX', mid: '000V9C4k1fgoAS', interval: 105 },
            { name: '重力失控 Weightless Chaos', singer: 'HOYO-MiX', mid: '002AMDmi08BIwd', interval: 70 },
            { name: '万花宇宙 Universal Kaleidoscope', singer: 'HOYO-MiX', mid: '001NOHcl39N0U7', interval: 67 },
            { name: '弹射起步 Catapult Launch', singer: 'HOYO-MiX', mid: '003vM2tU2m60jL', interval: 73 },
            { name: '美梦秘境 Dreamjoy Realm', singer: 'HOYO-MiX', mid: '003wFl9L0wJ2BC', interval: 81 },
            { name: '大地的温柔 The Gentle Earth', singer: 'HOYO-MiX', mid: '0035c3HC42a741', interval: 87 },
            { name: '嘻戏时刻 Playful Moments', singer: 'HOYO-MiX', mid: '001F1TGw2xOmh2', interval: 87 }
        ]
    },
    {
        name: '二相乐园',
        icon: '🎡',
        songs: [
            { name: '天生鬼才', singer: '萧敬腾 / HOYO-MiX', mid: '001FLItD3sFnnZ', interval: 154 },
            { name: '下一站 Beyond This Station', singer: '小林未郁 / HOYO-MiX', mid: '001kBUZh3wh2Qw', interval: 229 },
            { name: '下一站 Beyond This Station (伴奏)', singer: 'HOYO-MiX', mid: '002ywlr422AInb', interval: 229 },
            { name: '欢笑合成乐 Comedy Symphony', singer: 'HOYO-MiX', mid: '001KPYum2X7GwP', interval: 147 },
            { name: '早上好，二相乐园！ Morning, Planarcadia!', singer: 'HOYO-MiX', mid: '000O768I4AFMFR', interval: 105 },
            { name: '松弛电波 Soothing Waves', singer: 'HOYO-MiX', mid: '001yRFcg0BhmgL', interval: 76 },
            { name: '购物频道 Shopping Channel', singer: 'HOYO-MiX', mid: '003WMqk00BqjvS', interval: 122 },
            { name: '元气注入 Vital Infusion', singer: 'HOYO-MiX', mid: '002Dfe6n1ZuPwD', interval: 67 },
            { name: '白日食堂 Daylight Diner', singer: 'HOYO-MiX', mid: '001CIa6t06zNKe', interval: 88 },
            { name: '再见的路口 Where We Part Ways', singer: 'HOYO-MiX', mid: '001YRmas4MrpPt', interval: 115 },
            { name: '生活在这里的理由 Reasons to Live Here', singer: 'HOYO-MiX', mid: '003qMiAi25rGCO', interval: 125 },
            { name: '艺术之种 Seeds of Artistry', singer: 'HOYO-MiX', mid: '003QxkLb1bqjfg', interval: 91 },
            { name: '笔尖幻想 Pen-Point Fantasy', singer: 'HOYO-MiX', mid: '003E8UJb3lEIVR', interval: 96 },
            { name: '灰尘与秘密 Dust and Secrets', singer: 'HOYO-MiX', mid: '001t6zYP1ujnSa', interval: 93 },
            { name: '迷雾重重 Misted Mysteries', singer: 'HOYO-MiX', mid: '003r0sQp0HtAVp', interval: 99 },
            { name: '泛黄旧忆 Faded Memories', singer: 'HOYO-MiX', mid: '002aKiB32OHQWM', interval: 124 },
            { name: '晶莹的汗滴 Crystal Sweatdrops', singer: 'HOYO-MiX', mid: '001RuTWV1sFsFb', interval: 91 },
            { name: '世界尽头酒馆 World\'s End Tavern', singer: 'HOYO-MiX', mid: '002Wm2jy0byZzi', interval: 114 },
            { name: '极乐 Paramount Bliss', singer: 'HOYO-MiX', mid: '001S2jz10wm5mG', interval: 112 },
            { name: '享受此刻 Savor the Moment', singer: 'HOYO-MiX', mid: '0047r8US03wi3P', interval: 100 },
            { name: '魂骨肉 Bone Marrow', singer: 'HOYO-MiX', mid: '003PPibm2XRkOr', interval: 117 },
            { name: '稀世之物 Rare Treasure', singer: 'HOYO-MiX', mid: '0044i2OZ2U0pFP', interval: 115 },
            { name: '暗巷 Dark Alley', singer: 'HOYO-MiX', mid: '004RLvSE2Utl9j', interval: 70 },
            { name: '光的背面 The Dark Side of Light', singer: 'HOYO-MiX', mid: '0036jY074XeuDs', interval: 101 },
            { name: '花间梦旧事 A Dream Among Flowers', singer: 'HOYO-MiX', mid: '0008gWHj1XG3BL', interval: 109 },
            { name: '水中月 Water-Mirrored Moon', singer: 'HOYO-MiX', mid: '000t2WB80FnAAA', interval: 97 },
            { name: '祸兮福兮 Woe and Weal', singer: 'HOYO-MiX', mid: '00036JnB4OJxiU', interval: 105 },
            { name: '未济 Trigram of Incompletion', singer: 'HOYO-MiX', mid: '003RPKhe3zFxXC', interval: 91 },
            { name: '游戏时间到 Game Time!', singer: 'HOYO-MiX', mid: '003JCOEx1nmqwg', interval: 100 },
            { name: '上上下下左左右右 Up-Up-Down-Down-Left-Left-Right-Right', singer: 'HOYO-MiX', mid: '00130ZWb0ZWRGS', interval: 103 },
            { name: '飞跃天际线 Soaring Beyond the Skyline', singer: 'HOYO-MiX', mid: '002192ot1C2fK4', interval: 87 },
            { name: '全城通缉 Most Wanted', singer: 'HOYO-MiX', mid: '003KFsHz0vhrEQ', interval: 98 },
            { name: '白日梦 Daydream', singer: 'HOYO-MiX', mid: '000z18fI2aSSWT', interval: 50 },
            { name: '魔术空间 Magic Zone', singer: 'HOYO-MiX', mid: '003VXudD4deogh', interval: 49 },
            { name: '午夜迷离 Midnight Blur', singer: 'HOYO-MiX', mid: '000GCcLI2dNOcX', interval: 49 },
            { name: '新手教学 Tutorial', singer: 'HOYO-MiX', mid: '002L3rl20zgxsw', interval: 98 },
            { name: '火力全开 Maximum Firepower', singer: 'HOYO-MiX', mid: '003hvMtQ3CPqGi', interval: 40 },
            { name: '汗颜 Embarrassment', singer: 'HOYO-MiX', mid: '003jBUMM2U6nyj', interval: 86 },
            { name: '凝固的空气 Congealed Air', singer: 'HOYO-MiX', mid: '000Uxzk00dlnzv', interval: 85 },
            { name: '漫谈 Chatter', singer: 'HOYO-MiX', mid: '0047ehh444eppZ', interval: 120 },
            { name: '屏住呼吸 Held Breath', singer: 'HOYO-MiX', mid: '001JHVLW48fRLg', interval: 98 },
            { name: '乐园散步 A Walk in Paradise', singer: 'HOYO-MiX', mid: '001JA5141fhgCD', interval: 95 },
            { name: '人生终点站 Terminal of Life', singer: 'HOYO-MiX', mid: '0046kZmy3QWKe0', interval: 118 },
            { name: '节目效果 All for the Show', singer: 'HOYO-MiX', mid: '000y8Of02LSG1o', interval: 111 },
            { name: '灵机一动 Flash of Inspiration', singer: 'HOYO-MiX', mid: '000hvNPo2aUk5a', interval: 75 },
            { name: '网络迷因 Internet Meme', singer: 'HOYO-MiX', mid: '003QfrVW0UDy6x', interval: 49 },
            { name: '完美偶像 Perfect Idol', singer: 'HOYO-MiX', mid: '002S6d2R104Pz7', interval: 119 },
            { name: '肆意生长 Unbridled Growth', singer: 'HOYO-MiX', mid: '003m74BJ449MnJ', interval: 142 },
            { name: '死与新生 Death and Rebirth', singer: 'HOYO-MiX', mid: '004V0lJk32bdXa', interval: 122 },
            { name: '快乐的终点 Happy Destination', singer: 'HOYO-MiX', mid: '002nyKkj3Jr6A1', interval: 113 },
            { name: '瑞雪 Auspicious Snow', singer: 'HOYO-MiX', mid: '001NX7eI1EBSoT', interval: 103 },
            { name: '盛会约定 A Grand Promise', singer: 'HOYO-MiX', mid: '002bq94R3w6f3I', interval: 126 },
            { name: '指尖跃动 Dancing Fingertips', singer: 'HOYO-MiX', mid: '000Q2C0G0zN2lk', interval: 51 },
            { name: '银河泛舟 Cosmic Cruise', singer: 'HOYO-MiX', mid: '000bxadD1iS46o', interval: 86 },
            { name: '龙游寒渊 Dragon in the Frozen Deep', singer: 'HOYO-MiX', mid: '000CJCMv0iBL29', interval: 104 },
            { name: '正义间的对决 A Duel of Justice', singer: 'HOYO-MiX', mid: '001kzync2mTOpS', interval: 98 },
            { name: '遗忘之地 Land of the Forgotten', singer: 'HOYO-MiX', mid: '002boJ1v2J74j6', interval: 109 },
            { name: '钢铁与决心 Steel and Resolve', singer: 'HOYO-MiX', mid: '0022QKPK21oxhA', interval: 139 },
            { name: '英雄集合 Heroes Assemble', singer: 'HOYO-MiX', mid: '004W9ztO0ahOSa', interval: 96 },
            { name: '英雄出击 Heroic Strike', singer: 'HOYO-MiX', mid: '003EsDTS0PIvvp', interval: 96 },
            { name: '含珠 Hidden Pearl', singer: 'HOYO-MiX', mid: '002AwHnF2iaq5M', interval: 104 },
            { name: '如絮往事 Drifting Memories', singer: 'HOYO-MiX', mid: '0011f5h43sfyrx', interval: 143 },
            { name: '半杯热饮 Half-Cup of Simmering Hotness', singer: 'HOYO-MiX', mid: '000GTnsG2d3IhN', interval: 115 },
            { name: '折足之伤 Crippling Injury', singer: 'HOYO-MiX', mid: '001DvvA50WqxYa', interval: 61 },
            { name: '幸福！幸福！ Happy! Happy!', singer: 'HOYO-MiX', mid: '002KWI4s4BKBn0', interval: 102 },
            { name: '听！引擎在轰鸣 Listen! The Engines Roar!', singer: 'HOYO-MiX', mid: '003DkIGk3Oyryk', interval: 121 },
            { name: '超频节奏 Overclock Rhythm', singer: 'HOYO-MiX', mid: '0012THUx0hCSaZ', interval: 106 },
            { name: '海滨小城 Seaside Town', singer: 'HOYO-MiX', mid: '001oPafl2KBsrr', interval: 116 },
            { name: '飘浮 Floating', singer: 'HOYO-MiX', mid: '003hfw8m2Lyovo', interval: 73 },
            { name: '空洞电波 Hollow Waves', singer: 'HOYO-MiX', mid: '003TQVJ51SgB8b', interval: 97 },
            { name: '无人的景观 Deserted Landscape', singer: 'HOYO-MiX', mid: '001jpRlF3Fx3Ck', interval: 101 },
            { name: '大传媒时代 The Age of Mass Media', singer: 'HOYO-MiX', mid: '004fRIQI20JiDj', interval: 74 },
            { name: '娱乐至死 Amusing Ourselves to Death', singer: 'HOYO-MiX', mid: '0017tf5X3x89ZD', interval: 77 },
            { name: '异度骇入 Dimensional Hack', singer: 'HOYO-MiX', mid: '001jW2Rk2SOBe0', interval: 104 },
            { name: '幕后的操偶师 Unseen Puppeteer', singer: 'HOYO-MiX', mid: '0033P8xP2wpx0g', interval: 90 },
            { name: '民意的宝座 Throne of Public Opinion', singer: 'HOYO-MiX', mid: '003AMzzj4JZz7S', interval: 108 },
            { name: '众愿的顶峰 Pinnacle of All Wishes', singer: 'HOYO-MiX', mid: '002qqhvm0wkr5S', interval: 102 },
            { name: '居高临下 Condescending', singer: 'HOYO-MiX', mid: '003aNAth2Ollnl', interval: 87 },
            { name: '地平线的光 Light of the Horizon', singer: 'HOYO-MiX', mid: '003jTtEd3VOnMV', interval: 80 },
            { name: '剑歌悠远 Distant Sword Song', singer: 'HOYO-MiX', mid: '001KOs0i05jjUG', interval: 147 },
            { name: '泉隐秘境 The Hermitage', singer: 'HOYO-MiX', mid: '002REVLq2tqwxL', interval: 111 },
            { name: '留白 Blank Space', singer: 'HOYO-MiX', mid: '003TqCY112V2wO', interval: 112 },
            { name: '生于斯，长于斯 Born Here, Raised Here', singer: 'HOYO-MiX', mid: '004AIvYk14XTFc', interval: 116 },
            { name: '炉中故里 Hometown in the Hearth', singer: 'HOYO-MiX', mid: '002fp1fa4PAM5d', interval: 124 },
            { name: '漫不经心 Halfhearted Blow', singer: 'HOYO-MiX', mid: '0025SS0X2lRM3o', interval: 52 },
            { name: '彻骨 Bone Deep', singer: 'HOYO-MiX', mid: '002j2aSM2otdYm', interval: 87 },
            { name: '雪与血 Snow and Blood', singer: 'HOYO-MiX', mid: '0040bv1Q4ADRTe', interval: 87 },
            { name: '沉渊 Sunken Abyss', singer: 'HOYO-MiX', mid: '002lW8TQ0Lszhg', interval: 84 },
            { name: '天工淬炼 Skycraft Tempering', singer: 'HOYO-MiX', mid: '001NCvr44Ta9ff', interval: 117 },
            { name: '布施永生 Bestowal of Immortality', singer: 'HOYO-MiX', mid: '003XZcDX2aNLBx', interval: 91 },
            { name: '始作画者 The Founding Artist', singer: 'HOYO-MiX', mid: '002vyHl74KVpJH', interval: 123 },
            { name: '悬于兽口 Hanging in the Beast\'s Maw', singer: 'HOYO-MiX', mid: '001XmD6f2baaXF', interval: 233 },
            { name: '妖都狂宴 Demonhold\'s Revelry', singer: 'HOYO-MiX', mid: '003U5EAA2LidUD', interval: 165 },
            { name: '片刻喘息 A Moment\'s Respite', singer: 'HOYO-MiX', mid: '0049epkG0t54TJ', interval: 102 },
            { name: '虚构废墟 Imaginary Ruins', singer: 'HOYO-MiX', mid: '0033CTPX3vYSHr', interval: 99 },
            { name: '攀上雷霆 Climb the Thunders', singer: 'HOYO-MiX', mid: '001I5U7X1UiXDZ', interval: 89 },
            { name: '黄金分割的午后 An Afternoon of Golden Ratio', singer: 'HOYO-MiX', mid: '004ctr9p33AiuO', interval: 108 },
            { name: '未有之蓝图 Uncharted Blueprint', singer: 'HOYO-MiX', mid: '000tGUbe17gtwT', interval: 91 },
            { name: '风化旧梦 Weathered Old Dreams', singer: 'HOYO-MiX', mid: '002ar58Z3MBHut', interval: 112 },
            { name: '远眺深蓝 Gazing into the Deep Blue', singer: 'HOYO-MiX', mid: '004UGIOD4R7pHG', interval: 107 },
            { name: '最后嘱托 Final Request', singer: 'HOYO-MiX', mid: '000shcKY4RDLII', interval: 90 },
            { name: '坠星的摇篮 Fallen Star\'s Cradle', singer: 'HOYO-MiX', mid: '004Qemsd32zKGz', interval: 147 },
            { name: '命运的反诘 Destiny\'s Retort', singer: 'HOYO-MiX', mid: '002KIW2S035zua', interval: 76 },
            { name: '多闻我慢 Erudite Hubris', singer: 'HOYO-MiX', mid: '003CAYnQ2nZbVv', interval: 113 },
            { name: '万色返空 Saṃvartasthāyi', singer: 'HOYO-MiX', mid: '004b7Mca3YdlS2', interval: 131 },
            { name: '归于寂灭 Return to Silence', singer: 'HOYO-MiX', mid: '003DqlGm2hqCaT', interval: 187 },
        ]
    },
    {
        name: '模拟宇宙',
        icon: '🌀',
        desc: '求你了，来测吧！',
        songs: [
            { name: '灵魂深处', singer: 'HOYO-MiX', mid: '001Q9eLh093nd5', interval: 67 },
            { name: '沉浸感', singer: 'HOYO-MiX', mid: '00091vd22xeUc9', interval: 90 },
            { name: '悬疑电影', singer: 'HOYO-MiX', mid: '002l0Ful0H7rSj', interval: 93 },
            { name: '险象环生', singer: 'HOYO-MiX', mid: '0001PZo60KB9Fm', interval: 82 },
            { name: '另类摇滚', singer: 'HOYO-MiX', mid: '004UYqmx26b9mU', interval: 78 },
            { name: '原始的金黄 Primordial Resplendence', singer: 'HOYO-MiX', mid: '001dNmFg3c4dR7', interval: 112 },
            { name: '蛀星旧梦 Oneiros of Borehole Planet', singer: 'HOYO-MiX', mid: '001EyuCe1ar78o', interval: 88 },
            { name: '帝皇遗梦 Emperor\'s Reverie', singer: 'HOYO-MiX', mid: '004PE9ua2UWXY8', interval: 112 },
            { name: '千面英雄 Protean Hero', singer: 'HOYO-MiX', mid: '003lANAb0b7kF9', interval: 93 }
        ]
    },
    {
        name: '逐光捡金 & 货币战争',
        icon: '🎲',
        desc: '看什么看？深渊满星了吗？王棋0t了吗？',
        songs: [
            { name: '玄牝之门,万类之根 Arteria Inceptionis', singer: 'HOYO-MiX', mid: '000vuWJa3zqMgK', interval: 123 },
            { name: '倒转的时刻 Reversed Moments', singer: 'HOYO-MiX', mid: '001BhClt29zcju', interval: 100 },
            { name: '神圣裁决 Divine Judgment', singer: 'HOYO-MiX', mid: '0003GkDU4Cxyp8', interval: 104 },
            { name: '名与利 Fame and Fortune', singer: 'HOYO-MiX', mid: '000Dy0n31MySRx', interval: 95 },
            { name: '无形之手 Invisible Hand', singer: 'HOYO-MiX', mid: '002ojcql0PGUtA', interval: 93 }
        ]
    },
    {
        name: '千星纪游',
        icon: '✨',
        songs: [
            { name: '五龙远徙 Exodus of the Five Dragons', singer: 'HOYO-MiX', mid: '001wkKie3VIeVy', interval: 178 },
            { name: '说剑 On Swords', singer: 'HOYO-MiX', mid: '0046qo8N3XJKw6', interval: 136 },
            { name: '甄选、规划和机遇 Selection, Planning, and Opportunity', singer: 'HOYO-MiX', mid: '000izMwN0xjZRz', interval: 171 },
            { name: '耶佩拉叛乱 The Jepella Rebellion', singer: 'HOYO-MiX', mid: '003FCBlS19BgaL', interval: 172 },
            { name: '有关星空的寓言集•其一 Fables About the Stars Part 1', singer: 'HOYO-MiX', mid: '0015ataL1fxI52', interval: 230 },
            { name: '花火：幕后纪录 Sparkle: Behind the Curtain', singer: 'HOYO-MiX', mid: '001hg6733ankfA', interval: 164 },
            { name: '旧梦重温 A Revisiting of Past Dreams', singer: 'HOYO-MiX', mid: '001BFtuX4ankxN', interval: 135 },
            { name: '阮声落华裳，梅出似点妆 Transcendent Ruan Tunes, Blushing Mei Blooms', singer: 'HOYO-MiX', mid: '002xV1qC423FnI', interval: 175 },
            { name: '虚谭•浮世三千一刀缭断 Kyoden: A Cleave Across the Transient World', singer: 'HOYO-MiX', mid: '003Jvv1l3NdyGg', interval: 222 },
            { name: '永火一夜：第33场 A Night of Ever-Flame: Scene 33', singer: 'HOYO-MiX', mid: '000t4mEt2IcNqu', interval: 181 },
            { name: '飞镝追星 The Arrow that Seeks the Stars', singer: 'HOYO-MiX', mid: '002POW8t2mbWGM', interval: 142 },
            { name: '假若有一双翅膀 If We Had Wings', singer: 'HOYO-MiX', mid: '003UYeaH09KK2K', interval: 180 },
            { name: '石心誓环•天平两端 Stoneheart\'s Oath Ring: Both Ends of the Scale', singer: 'HOYO-MiX', mid: '003FyCbe36ms60', interval: 195 },
            { name: '天干剑燥，小心火炉 Mind the Swelter, Watch the Furnace', singer: 'HOYO-MiX', mid: '002r7D7L34Wror', interval: 149 },
            { name: '此刻，在同一片星空下 Presently, Beneath a Shared Sky of Stars', singer: 'HOYO-MiX', mid: '003DzZLx1zROLH', interval: 176 },
            { name: '不似一片浮云 Unlike a Floating Cloud', singer: 'HOYO-MiX', mid: '002cKV8H0bbZcZ', interval: 166 },
            { name: '群星静默如谜 Stars, Silent as Enigmas', singer: 'HOYO-MiX', mid: '004Y4eEf29pEAk', interval: 176 },
            { name: '太阳落下之后 After the Sunset', singer: 'HOYO-MiX', mid: '003tn0GH0dxeBZ', interval: 209 },
            { name: '故事之外：第8场 Exotale: Scene 8', singer: 'HOYO-MiX', mid: '0015LSkp1z2w5b', interval: 254 },
            { name: '亲爱的三月七 Dear March 7th', singer: 'HOYO-MiX', mid: '000vyHuY0nDnx8', interval: 151 },
            { name: '有关星空的寓言集•其二 Fables About the Stars Part 2', singer: 'HOYO-MiX', mid: '001OQaz13l3ceK', interval: 294 },
            { name: '星际和平倡议：反毁灭同盟 Anti-Destruction Alliance', singer: 'HOYO-MiX', mid: '000k8Rhc0zC9qu', interval: 171 },
            { name: '第999场：GAME NOT OVER', singer: 'HOYO-MiX', mid: '000Z5nxM2yHNei', interval: 239 },
        ]
    },
    {
        name: '动画短片',
        icon: '🎬',
        songs: [
            { name: '飞光 A Flash', singer: 'HOYO-MiX', mid: '004AiByv3gqgfl', interval: 189 },
            { name: '玄黄 Ichor of Two Dragons', singer: 'HOYO-MiX', mid: '0011mE2G3MzxqV', interval: 233 },
            { name: '永劫轮舞 Rondo Across Countless Kalpas', singer: 'HOYO-MiX', mid: '001vMV7K0dHwzJ', interval: 195 },
            { name: '太平临新岁 Harmony Greets the New Year', singer: 'HOYO-MiX', mid: '001gQcfY2XcYVQ', interval: 197 },
            { name: '格拉默的余烬 The Embers of Glamoth', singer: 'HOYO-MiX', mid: '004CInOl3dkpcH', interval: 190 },
            { name: '清闲自在身 Taking It Easy', singer: 'HOYO-MiX', mid: '0032F7Uk0d3gqF', interval: 209 },
            { name: '那安息的长夜 The Long Night of Serenity', singer: 'HOYO-MiX', mid: '002xnNNu0a21Ea', interval: 399 },
            { name: '大黑塔的魔法厨房 The Herta\'s Magic Kitchen', singer: 'HOYO-MiX', mid: '003xW4QG3JxOld', interval: 166 },
            { name: '银河忍法帖•乱武驱魔破邪斩月之卷 Cosmic Ninjutsu Inscriptions — Havoc Exorcism Lunar Vileslayer Scroll', singer: 'HOYO-MiX', mid: '0008YBmz3N5Bjo', interval: 157 },
            { name: '耀斑', singer: 'HOYO-MiX / YMIR', mid: '0032XEmk1aJvq1', interval: 213 },
            { name: '跋涉 Trek', singer: 'HOYO-MiX', mid: '0006cl4U3SUwyI', interval: 138 },
            { name: '昔涟', singer: '张韶涵 / HOYO-MiX', mid: '002rhFKO3EjKAg', interval: 186 },
            { name: 'Ripples of Past Reverie 昔涟', singer: 'Cassie Wei / HOYO-MiX', mid: '0035IPcT2ONQJ2', interval: 186 },
            { name: '死于午后 Death in the Afternoon', singer: 'HOYO-MiX', mid: '000VwQP43PYRwk', interval: 154 },
            { name: '这游戏还能不能玩了？ Is This Game Even Playable?', singer: 'HOYO-MiX', mid: '002d9FFI2sSeVW', interval: 240 },
            { name: '你的终点，我的起点 Your Ending, My Beginning', singer: 'HOYO-MiX', mid: '001WQ9k40zVpck', interval: 445 },
        ]
    },
    {
        name: '知更鸟的歌',
        icon: '🐦',
        desc: '所有人，玩气球！',
        songs: [
            { name: '使一颗心免于哀伤', singer: '知更鸟 / HOYO-MiX / Chevy', mid: '000E9VjK3W0Ez0', interval: 202 },
            { name: '在银河中孤独摇摆', singer: '知更鸟 / HOYO-MiX / Chevy', mid: '003Xspep2oKRxi', interval: 165 },
            { name: '若我不曾见过太阳', singer: '知更鸟 / HOYO-MiX / Chevy', mid: '003GiEd42liN7V', interval: 145 },
            { name: '希望有羽毛和翅膀', singer: '知更鸟 / HOYO-MiX / Chevy', mid: '004ArOCZ13Lvqo', interval: 229 },
            { name: '唯有追赶风的方向', singer: '知更鸟 / HOYO-MiX / Chevy', mid: '000M3Yxt2tIuHZ', interval: 123 }
        ]
    },
    {
        name: '列车曲',
        icon: '🚂',
        desc: '星穹列车，允许发车',
        songs: [
            { name: '星间旅行 (中文版)', singer: 'HOYO-MiX / 茶理理', mid: '0015kalN25tYq8', interval: 92 },
            { name: '星间旅行 (英文版)', singer: 'HOYO-MiX / Lea Sirk', mid: '0029wCxS38uzSp', interval: 92 },
            { name: '不虚此行 On the Journey', singer: '魏晨 / Nea / HOYO-MiX', mid: '0049lelQ3EY4jN', interval: 156 }
        ]
    },
    {
        name: '角色 PV 曲',
        icon: '🎭',
        tagLabel: 'PV角色',
        songs: [
            { name: '来，拍照啦！ Let\'s Take a Photo!', singer: 'HOYO-MiX', mid: '003f1hyl1wNU5g', interval: 89, tag: '三月七' },
            { name: '引爆在即！ The Cusp of Ignition!', singer: 'HOYO-MiX', mid: '001akceH0KK4YO', interval: 50, tag: '希露瓦' },
            { name: '天干物燥 In Torrid Heat', singer: 'HOYO-MiX', mid: '000lHx8F0uQi0v', interval: 84, tag: '白露' },
            { name: '锋寒砺淬 Tempered Chill', singer: 'HOYO-MiX', mid: '000yZZSI4XIVr1', interval: 64, tag: '彦卿' },
            { name: '追星星的人 Star Chaser', singer: 'HOYO-MiX', mid: '0000zwqb40sLH0', interval: 78, tag: '姬子' },
            { name: '以朗道之名 In the Name of Landau', singer: 'HOYO-MiX', mid: '004EOvdG25FcpI', interval: 73, tag: '杰帕德' },
            { name: '一夜无事 Uneventful Night', singer: 'HOYO-MiX', mid: '003ZH3l31tTUWv', interval: 85, tag: '希儿' },
            { name: '天地为枰 Heaven and Earth as a Chessboard', singer: 'HOYO-MiX', mid: '004R0M2G1wWHFZ', interval: 115, tag: '景元' },
            { name: '有点意思 Got a Date', singer: 'HOYO-MiX', mid: '003ZiSrF28fxSz', interval: 86, tag: '银狼' },
            { name: '行者明誓 The Traveler And His Oath', singer: 'HOYO-MiX', mid: '003tXnaQ2kjplJ', interval: 107, tag: '罗刹' },
            { name: '死兆将至 Death Approaches', singer: 'HOYO-MiX', mid: '003tpuXV4HWF6G', interval: 109, tag: '刃' },
            { name: '戏剧性反讽 A Dramatic Irony', singer: 'HOYO-MiX', mid: '002uvaJj0vzhos', interval: 112, tag: '卡芙卡' },
            { name: '归去来 The Prodigal\'s Return', singer: 'HOYO-MiX', mid: '000fANhE3vhkHl', interval: 103, tag: '丹恒·饮月' },
            { name: '法眼无遗 Omniscia Spares None', singer: 'HOYO-MiX', mid: '001TxPVg1v4i3r', interval: 106, tag: '符玄' },
            { name: '剑出无回 Swordward', singer: 'HOYO-MiX', mid: '0030Jf4n3s0foL', interval: 108, tag: '镜流' },
            { name: '回魂夜 Night of Thrills', singer: 'HOYO-MiX', mid: '0021jTvQ33Vsre', interval: 108, tag: '藿藿' },
            { name: '骑士文学 Chivalric Romances', singer: 'HOYO-MiX', mid: '003orWxi0szDb5', interval: 109, tag: '银枝' },
            { name: '专家教学 Expert Tutorial', singer: 'HOYO-MiX', mid: '000UMWnL4M0UnJ', interval: 107, tag: '托帕' },
            { name: '万物生 In All Does Life Flow', singer: 'HOYO-MiX', mid: '002rOxQm2exvBj', interval: 103, tag: '阮·梅' },
            { name: '愚不可及 Supreme Idiocy', singer: 'HOYO-MiX', mid: '001wbQNM2MMxVA', interval: 103, tag: '真理医生' },
            { name: '摇篮曲 Lullaby', singer: 'HOYO-MiX', mid: '001vasf13fJqUS', interval: 110, tag: '黑天鹅' },
            { name: '独角戏 Monodrama', singer: 'HOYO-MiX', mid: '0007nqC02aoCZ9', interval: 119, tag: '花火' },
            { name: '你的颜色', singer: 'HOYO-MiX', mid: '004NUI9T1dDtxI', interval: 158, tag: '黄泉' },
            { name: '金手指 The Golden Touch', singer: 'HOYO-MiX', mid: '000Eb5qZ1qaSLL', interval: 123, tag: '砂金' },
            { name: '牛仔很忙 Cowboy\'s Got Business', singer: 'HOYO-MiX', mid: '003vUO961P05Pl', interval: 117, tag: '波提欧' },
            { name: '壳中萤火 Embers in a Shell', singer: 'HOYO-MiX', mid: '001qNrEr1Bh5AN', interval: 174, tag: '流萤' },
            { name: '欲望收藏 A Collection of Desires', singer: 'HOYO-MiX', mid: '002rIp4G25dumb', interval: 117, tag: '翡翠' },
            { name: '误打误撞 Serendipity', singer: 'HOYO-MiX', mid: '004LK8Ps2ku0C6', interval: 128, tag: '云璃' },
            { name: '销魂饭 Pneumanull Rice', singer: 'HOYO-MiX', mid: '004boRlU0QVpBJ', interval: 111, tag: '椒丘' },
            { name: '君莫笑 Nothing to Laugh At', singer: 'HOYO-MiX', mid: '0020xWjJ4L7eA4', interval: 189, tag: '飞霄' },
            { name: '燎沉香 Burning Scent of Home', singer: 'HOYO-MiX', mid: '004XsyPb0nCpSE', interval: 127, tag: '灵砂' },
            { name: '不乱不破', singer: 'HOYO-MiX / Reol', mid: '0025taaD2uLfbu', interval: 138, tag: '乱破' },
            { name: '子不语 Wordless', singer: 'HOYO-MiX', mid: '003M0zbR4bbaC7', interval: 132, tag: '忘归人' },
            { name: '独奏者 Soloist', singer: 'HOYO-MiX', mid: '001Oe5hu0i0vkc', interval: 130, tag: '星期日' },
            { name: '宇宙有天才 Geniuses in the Universe', singer: 'HOYO-MiX', mid: '001uMOtE3HDKCP', interval: 144, tag: '大黑塔' },
            { name: '致命浪漫 Deadly Romance', singer: 'HOYO-MiX', mid: '000oFsrs3qKlNH', interval: 144, tag: '阿格莱雅' },
            { name: '童言无忌 Children Know Nothing', singer: 'HOYO-MiX', mid: '001jfFg22s8Ynh', interval: 121, tag: '缇宝' },
            { name: '人之怒 Wrath of Man', singer: 'HOYO-MiX', mid: '000m2Wxb0pVeLF', interval: 111, tag: '万敌' },
            { name: '墓志铭 Epitaph', singer: 'HOYO-MiX', mid: '002wM1rS20zQQT', interval: 176, tag: '遐蝶' },
            { name: '何罪之有 The Sin of Pride', singer: 'HOYO-MiX', mid: '002rvGsD3cqirR', interval: 128, tag: '那刻夏' },
            { name: '有求必应 Always Here to Help', singer: 'HOYO-MiX', mid: '00181GwU1bxGb1', interval: 106, tag: '风堇' },
            { name: '举手之劳 Piece of Cake', singer: 'HOYO-MiX', mid: '003J3X9U0Rdz0s', interval: 115, tag: '赛飞儿' },
            { name: '日冕 Coronal Radiance', singer: 'HOYO-MiX', mid: '003DwDB52GvD1y', interval: 200, tag: '白厄' },
            { name: '海的女儿 Daughter of the Sea', singer: 'HOYO-MiX', mid: '002HO3SZ1h3Cbi', interval: 136, tag: '海瑟音' },
            { name: '以身入局 Step Onto the Board', singer: 'HOYO-MiX', mid: '002AmSEj2UU0BF', interval: 131, tag: '刻律德菈' },
            { name: '天黑请闭眼 Night Falls, Everyone, Close Your Eyes', singer: 'HOYO-MiX', mid: '002NBWiX0FtsTH', interval: 133, tag: '长夜月' },
            { name: '归处 Home', singer: 'HOYO-MiX', mid: '001e7z382Pfmvx', interval: 135, tag: '丹恒·腾荒' },
            { name: '再度和你 With You Once More', singer: 'HOYO-MiX', mid: '000vrQZI2oqlhM', interval: 204, tag: '昔涟' },
            { name: '一曲终了 The Final Note', singer: 'HOYO-MiX', mid: '002JEo2H1rXuXM', interval: 119, tag: '大丽花' },
            { name: '万事如意 All the Best', singer: 'HOYO-MiX', mid: '002iky9W3dGC8J', interval: 116, tag: '爻光' },
            { name: '痴人说梦', singer: 'HOYO-MiX', mid: '002Kgaz04dXb1Z', interval: 115, tag: '花火' },
            { name: '狼来了 The Wolf is Coming', singer: 'HOYO-MiX', mid: '002m7GN00hO2tb', interval: 102, tag: '不死途' },
            { name: '我独自满级 Solo Maxxing', singer: 'hanser / HOYO-MiX', mid: '000ltsTu4aYuVq', interval: 160, tag: '银狼lv.999' },
            { name: '她的日常 Her Daily Life', singer: 'HOYO-MiX', mid: '000qAjj004f3qD', interval: 101, tag: '绯英' },
            { name: '灭度 Nirvana', singer: 'HOYO-MiX', mid: '003ahnBi3XMtsO', interval: 99, tag: '千冶·刃' },
            { name: '启明星于今夜坠落 The Morning Star Falls Tonight', singer: 'HOYO-MiX', mid: '0045ZT3H1REO3J', interval: 200, tag: '姬子·启行' },
            { name: '唯有追赶风的方向 Only By Chasing the Wind', singer: '知更鸟 / HOYO-MiX / Chevy', mid: '000M3Yxt2tIuHZ', interval: 123, tag: '知更鸟·晴歌' },
        ]
    },
    {
        name: '版本PV',
        icon: '🎞️',
        tagLabel: '版本',
        songs: [
            { name: '银河漫游 Galactic Roaming', singer: 'HOYO-MiX', mid: '0047skD54AdSss', interval: 107, tag: '1.1' },
            { name: '仙骸有终 Even Immortality Ends', singer: 'HOYO-MiX', mid: '003fvjtX2PqxDQ', interval: 103, tag: '1.2' },
            { name: '天镜映劫尘 Celestial Eyes Above Mortal Ruins', singer: 'HOYO-MiX', mid: '003lnjSC2fNM9f', interval: 101, tag: '1.3' },
            { name: '冬梦激醒 Jolted Awake From a Winter Dream', singer: 'HOYO-MiX', mid: '004RkVAK2rMuZF', interval: 171, tag: '1.4' },
            { name: '迷离幻夜谈 The Crepuscule Zone', singer: 'HOYO-MiX', mid: '0046jmZN0KKds2', interval: 163, tag: '1.5' },
            { name: '庸与神的冠冕 Crown of the Mundane and Divine', singer: 'HOYO-MiX', mid: '002V2yzG1oFg5r', interval: 84, tag: '1.6' },
            { name: '不眠之夜', singer: '张杰 / HOYO-MiX', mid: '0032wpIs0D30HZ', interval: 138, tag: '2.0' },
            { name: '狂热奔向深渊 Into the Yawning Chasm', singer: 'HOYO-MiX', mid: '002RTNks3sVIRo', interval: 100, tag: '2.1' },
            { name: '等醒来再哭泣 Then Wake to Weep', singer: 'HOYO-MiX', mid: '003vjKCY2n701c', interval: 100, tag: '2.2' },
            { name: '再见，匹诺康尼 Farewell, Penacony', singer: 'HOYO-MiX', mid: '002YnMgH1BfSd6', interval: 93, tag: '2.3' },
            { name: '明霄竞武试锋芒 Finest Duel Under the Pristine Blue', singer: 'HOYO-MiX', mid: '000XFD8r4baRG5', interval: 93, tag: '2.4' },
            { name: '碧羽飞黄射天狼 Flying Aureus Shot to Lupine Rue', singer: 'HOYO-MiX', mid: '003yIETf35AeFg', interval: 90, tag: '2.5' },
            { name: '毗乃昆尼末法世记 Annals of Pinecany\'s Mappō Age', singer: 'HOYO-MiX', mid: '002lkIg94KV77m', interval: 155, tag: '2.6' },
            { name: '在第八日启程 A New Venture on the Eighth Dawn', singer: 'HOYO-MiX', mid: '002Sg7kP14JeXW', interval: 95, tag: '2.7' },
            { name: '何者', singer: '谭晶 / HOYO-MiX', mid: '003YIetk4CRlfq', interval: 146, tag: '3.0' },
            { name: '门扉之启，王座之终 Light Slips the Gate, Shadow Greets the Throne', singer: 'HOYO-MiX', mid: '001Yq3U21rzWIp', interval: 156, tag: '3.1' },
            { name: '走过安眠地的花丛 Through the Petals in the Land of Repose', singer: 'HOYO-MiX', mid: '004WLkjf4aN3fM', interval: 169, tag: '3.2' },
            { name: '在黎明升起时坠落 The Fall at Dawn\'s Rise', singer: 'HOYO-MiX', mid: '002Bz4EO4HkJ8G', interval: 173, tag: '3.3' },
            { name: '因为太阳将要毁伤 For the Sun is Set to Die', singer: 'HOYO-MiX', mid: '000U9OB91lhDax', interval: 178, tag: '3.4' },
            { name: '开拓者 Trailblazer', singer: 'HOYO-MiX', mid: '002G6gDY3EAzWY', interval: 100, tag: '救世' },
            { name: '于长夜重返大地 Back to Earth in Evernight', singer: 'HOYO-MiX', mid: '001yAkHb3uFaQY', interval: 176, tag: '3.6' },
            { name: '成为昨日的明天 As Tomorrow Became Yesterday', singer: 'HOYO-MiX', mid: '001o49Bs2ZiWEb', interval: 207, tag: '3.7' },
            { name: '记忆是梦的开场白 Memories are the Prelude to Dreams', singer: 'HOYO-MiX', mid: '002iP3yF24x9JI', interval: 162, tag: '3.8' },
            { name: '满月是神不在的时间 No Aha at Full Moon', singer: 'HOYO-MiX', mid: '000Z9Y5e2Lb6Gv', interval: 118, tag: '4.0' },
            { name: '献给破晓的失控 Unraveled for Daybreak', singer: 'HOYO-MiX', mid: '000dlAD63z9W6u', interval: 160, tag: '4.1' },
            { name: '如是，众生欢笑不已 So Laughed the Masses', singer: 'HOYO-MiX', mid: '0038Af7Z49GPua', interval: 199, tag: '4.2' },
            { name: '沉于生者的忘川 The Lethe Below the Living', singer: 'HOYO-MiX', mid: '003HCaPY0K4N1l', interval: 184, tag: '4.3' },
            { name: '鸣笛于归寂之时 In Ravages Does the Whistle Sound', singer: 'HOYO-MiX', mid: '003vB9q60D9s6o', interval: 233, tag: '4.4' }
        ]
    },
    {
        name: '黄金史诗 & 即兴巡演',
        icon: '🎬',
        songs: [
            { name: '翁法罗斯英雄纪 Amphoreus\' Saga of Heroes', singer: 'HOYO-MiX', mid: '003liAfV1ItJx8', interval: 287 },
            { name: '再见，昔涟 Farewell, Cyrene', singer: 'HOYO-MiX', mid: '001oztrG3RWEFG', interval: 155 },
            { name: '命运的第一个黎明 The First Dawn of Destiny', singer: 'HOYO-MiX', mid: '003icoeA0c7n1A', interval: 178 },
            { name: '生命从夜中醒来 Life Awakens from the Night', singer: 'HOYO-MiX', mid: '00055vx34TlgXs', interval: 230 },
            { name: '铁墓之战后，官方没有说出的真相！ The Truth After the Battle of Irontomb!', singer: 'HOYO-MiX', mid: '003Ny4bA0Gb0Pe', interval: 177 },
            { name: '吉凶之外 Beyond Weal and Woe', singer: 'HOYO-MiX', mid: '004Vtrdt3jIs0L', interval: 221 },
            { name: '新手指南 Beginner\'s Guide', singer: 'HOYO-MiX', mid: '002vG6lO1j4sLL', interval: 238 },
            { name: '欢愉之死 Death of the Elation', singer: 'HOYO-MiX', mid: '003vGK4w16elK9', interval: 209 },
            { name: '致仰望者 To the Onlooker', singer: 'HOYO-MiX', mid: '003cYzdr2TNSWA', interval: 224 },
        ]
    },
    {
        name: '其他 PV',
        icon: '📺',
        songs: [
            { name: '下一站，银河！', singer: 'HOYO-MiX', mid: '001nrAAQ3wYSsh', interval: 116 },
            { name: '你的选择 Your Choice', singer: 'HOYO-MiX', mid: '002vQ2n214HSAS', interval: 116 },
            { name: '致将启程的你 To You Who Will Soon Depart', singer: 'HOYO-MiX', mid: '0028Giaa4V6PVA', interval: 86 },
            { name: '太空喜剧 Space Comedy', singer: 'HOYO-MiX', mid: '004DD01C023kfp', interval: 84 },
            { name: '神策府总司一切大小事务将军 General of All Affairs at the Seat of Divine Foresight', singer: 'HOYO-MiX', mid: '002JqGHf3BySax', interval: 93 },
            { name: '掌中宇宙 Grasp the Stars', singer: 'HOYO-MiX', mid: '000Tbxaa2phntM', interval: 94 },
            { name: '常看常新的故事 A Story That Never Grows Dull', singer: 'HOYO-MiX', mid: '003nJJgM4D02vx', interval: 87 },
            { name: '一起出去玩嘛！ Wanna Go Have Some Fun!', singer: 'HOYO-MiX', mid: '002kWkN03GIDPt', interval: 84 },
            { name: '演出开始前 Before the Show Starts', singer: 'HOYO-MiX', mid: '004XUMVF0jN0qn', interval: 89 },
            { name: '做梦的艺术 Art of Dreaming', singer: 'HOYO-MiX', mid: '000znJdE37nxdE', interval: 90 },
            { name: '挑战，无处不在 Challenges Come Anywhere, Anytime', singer: 'HOYO-MiX', mid: '002ECMrc0KJXnq', interval: 64 },
            { name: '你所不曾抵达的世界 The Worlds You\'ve Never Been', singer: 'HOYO-MiX', mid: '003H9Q8D05PnlW', interval: 87 },
            { name: '拍摄进行中 Filming in Progress', singer: 'HOYO-MiX', mid: '003hOwxC2FsO3Q', interval: 94 },
            { name: '相见『很』晚 A Long \'Fated\' Meeting', singer: 'HOYO-MiX', mid: '000XSJNR0Pbi9u', interval: 138 },
            { name: '别来无恙 A Long Awaited Reunion', singer: 'HOYO-MiX', mid: '0005PDkl0pYQEI', interval: 139 },
        ]
    }
];
